# Generated by Django 4.1.4 on 2023-01-06 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('F_Name', models.TextField(max_length=30)),
                ('L_Name', models.TextField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('department', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerID', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('F_Name', models.TextField(max_length=30)),
                ('L_Name', models.TextField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('department', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('purchaserID', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('F_Name', models.TextField(max_length=30)),
                ('L_Name', models.TextField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('department', models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quoID', models.AutoField(primary_key=True, serialize=False)),
                ('delAddress', models.CharField(max_length=50)),
                ('formStatus', models.TextField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending')),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
                ('purchaserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('formID', models.AutoField(primary_key=True, serialize=False)),
                ('delAddress', models.CharField(max_length=50)),
                ('formStatus', models.TextField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending')),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
            ],
        ),
    ]
