# Generated by Django 4.1.4 on 2023-01-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_manager_purchaser_alter_item_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
