# Generated by Django 4.1.4 on 2023-01-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='managerID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='purchaserID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='formID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quoID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
