# Generated by Django 4.1.4 on 2023-01-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_empid_alter_item_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOfficer',
            fields=[
                ('financeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('F_Name', models.TextField(max_length=30)),
                ('L_Name', models.TextField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('department', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('zipCode', models.IntegerField()),
                ('State', models.TextField(max_length=30)),
                ('contactNum', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Quo_Item',
            fields=[
                ('itemID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.TextField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('quoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('orderID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('delAddress', models.CharField(max_length=50)),
                ('foID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
                ('vendorID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PR_Item',
            fields=[
                ('itemID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.TextField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('formID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchaserequisition')),
            ],
        ),
        migrations.CreateModel(
            name='PO_Item',
            fields=[
                ('itemID', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.TextField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('shipDate', models.DateField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
    ]
