# Generated by Django 4.1.4 on 2023-01-09 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_purchaserequisition_formdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='formID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quoDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
