# Generated by Django 4.1.4 on 2023-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quotation_formid_quotation_quodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contactNum',
            field=models.CharField(max_length=15),
        ),
    ]
