# Generated by Django 4.1.4 on 2023-01-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_formstatus_quotation_statusquo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vendID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='app.vendor'),
        ),
    ]
